AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/**/*.rb'
    - 'spec/spec_helper.rb'
    - 'spec/rails_helper.rb'
    - 'config/**/*.rb'
    - 'bin/*'
    - 'Gemfile'

Layout/IndentHash:
  Enabled: false

Layout/SpaceInsideHashLiteralBraces:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/BracesAroundHashParameters:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*.rb'

Metrics/LineLength:
  Enabled: false

Style/NegatedIf:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/AbcSize:
  Enabled: false
